INSERT INTO pessoa (cpf, email, nome) VALUES ('52955978140', 'varaujo@moderna.com.br', 'Valeria Mariana Costa Araújo');
INSERT INTO pessoa (cpf, email, nome) VALUES ('42254358499', 'francisca.gomes831@gmail.com', 'Francisca Gomes');
INSERT INTO pessoa (cpf, email, nome) VALUES ('35517480470', 'leticia.silva326@uol.com.br', 'Leticia Reis da Silva');
INSERT INTO pessoa (cpf, email, nome) VALUES ('28993765359', 'nelsonaraujo@bol.com.br', 'Nelson Arthur Cavalcanti Araújo');
INSERT INTO pessoa (cpf, email, nome) VALUES ('34119923100', 'mlima@hotmail.com', 'Mauricio de Jesus de Lima');
INSERT INTO pessoa (cpf, email, nome) VALUES ('08837594895', 'msouza@globo.com', 'Mauricio Sergio de Oliveira Souza de Souza');
INSERT INTO pessoa (cpf, email, nome) VALUES ('22462335773', 'vsantos@uol.com.br', 'Valeria Aline Teixeira Santos');
INSERT INTO pessoa (cpf, email, nome) VALUES ('49504041302', 'llopes@uol.com.br', 'Luis Moreno Campos Lopes');
INSERT INTO pessoa (cpf, email, nome) VALUES ('31966904231', 'camilacampos@moderna.com.br', 'Camila Vieira de Souza Campos');
INSERT INTO pessoa (cpf, email, nome) VALUES ('52642914208', 'amota@outlook.com', 'Antonio Pereira da Mota');
INSERT INTO pessoa (cpf, email, nome) VALUES ('28856634309', 'ccavalcanti@gmail.com', 'Caroline Sabrina Nascimento Cavalcanti');
INSERT INTO pessoa (cpf, email, nome) VALUES ('34689164347', 'marcos.teixeira347@moderna.com.br', 'Marcos Enzo de Souza Dias Teixeira');
INSERT INTO pessoa (cpf, email, nome) VALUES ('11122680651', 'jmelo@r7.com', 'Jaqueline Rodrigues de Lima Melo');
INSERT INTO pessoa (cpf, email, nome) VALUES ('82443024539', 'julio.carvalho@r7.com', 'Julio Carvalho de Carvalho');
INSERT INTO pessoa (cpf, email, nome) VALUES ('59133186847', 'mbarbosa@yahoo.com.br', 'Mauricio Cardoso Barbosa');
INSERT INTO pessoa (cpf, email, nome) VALUES ('59659163452', 'bcavalcanti@hotmail.com', 'Bruno Pereira Cavalcanti');
INSERT INTO pessoa (cpf, email, nome) VALUES ('68118448339', 'juliana_ramos@uol.com.br', 'Juliana Jessica dos Santos Ramos');
INSERT INTO pessoa (cpf, email, nome) VALUES ('36014197265', 'jcavalcanti@comercial.com.br', 'Jessica Rocha Cavalcanti');
INSERT INTO pessoa (cpf, email, nome) VALUES ('83038762954', 'daniel.monteiro247@negocio.com.br', 'Daniel Marcos Monteiro');
INSERT INTO pessoa (cpf, email, nome) VALUES ('25227463328', 'lucas.teixeira771@r7.com', 'Lucas da Costa Rocha Teixeira');
INSERT INTO pessoa (cpf, email, nome) VALUES ('70005856507', 'emota@corporativo.com.br', 'Eduardo Roberto da Mota');
INSERT INTO pessoa (cpf, email, nome) VALUES ('12045169367', 'joliveira@outlook.com', 'Julio Luis Moreira de Oliveira');
INSERT INTO pessoa (cpf, email, nome) VALUES ('30609420992', 'leonardo.araujo573@r7.com', 'Leonardo Ribeiro Araújo');
INSERT INTO pessoa (cpf, email, nome) VALUES ('19441082465', 'malves@ig.com.br', 'Marcelo Alves');
INSERT INTO pessoa (cpf, email, nome) VALUES ('46761199760', 'rafaelpinto@hotmail.com', 'Rafael José Pinto');
INSERT INTO pessoa (cpf, email, nome) VALUES ('12896378650', 'ali.dias237@corporativo.com.br', 'Ali Dias');
INSERT INTO pessoa (cpf, email, nome) VALUES ('31739227352', 'nteixeira@moderna.com.br', 'Natalia de Almeida Cavalcanti Teixeira');
INSERT INTO pessoa (cpf, email, nome) VALUES ('01560865229', 'sandragomes@comercial.com.br', 'Sandra de Souza Gomes');
INSERT INTO pessoa (cpf, email, nome) VALUES ('60080724647', 'sribeiro@ig.com.br', 'Simone Carvalho Ribeiro');
INSERT INTO pessoa (cpf, email, nome) VALUES ('56983084039', 'joao.barbosa304@empresa.com.br', 'João da Costa Barbosa');
INSERT INTO pessoa (cpf, email, nome) VALUES ('91688937790', 'julia_rodrigues@hotmail.com', 'Julia da Mota Pinto Rodrigues');
INSERT INTO pessoa (cpf, email, nome) VALUES ('86983519728', 'bruno.almeida@outlook.com', 'Bruno Eduardo de Moura Almeida');
INSERT INTO pessoa (cpf, email, nome) VALUES ('39796654296', 'rodrigosantos@empresa.com.br', 'Rodrigo Oliveira Santos');
INSERT INTO pessoa (cpf, email, nome) VALUES ('88072840738', 'pcavalcanti@gmail.com', 'Pedro João Pinto Cavalcanti');
INSERT INTO pessoa (cpf, email, nome) VALUES ('72597862216', 'julio_gomes@comercial.com.br', 'Julio Gomes');
INSERT INTO pessoa (cpf, email, nome) VALUES ('59143332455', 'renata.mota612@terra.com.br', 'Renata Ana Nascimento da Mota');
INSERT INTO pessoa (cpf, email, nome) VALUES ('28119097882', 'arthur_oliveira@bol.com.br', 'Arthur Gonçalves Oliveira');
INSERT INTO pessoa (cpf, email, nome) VALUES ('21308842295', 'julio.luz@comercial.com.br', 'Julio da Luz');
INSERT INTO pessoa (cpf, email, nome) VALUES ('14818924105', 'lauraaraujo@r7.com', 'Laura Gabriela Almeida Barbosa Araújo');
INSERT INTO pessoa (cpf, email, nome) VALUES ('80245381996', 'daniela_nascimento@r7.com', 'Daniela do Nascimento');
INSERT INTO pessoa (cpf, email, nome) VALUES ('93336229774', 'sabrina.pereira605@terra.com.br', 'Sabrina Correia Pereira');
INSERT INTO pessoa (cpf, email, nome) VALUES ('13806751544', 'cristianeteixeira@bol.com.br', 'Cristiane de Almeida Teixeira');
INSERT INTO pessoa (cpf, email, nome) VALUES ('57077938441', 'fabiopereira@moderna.com.br', 'Fabio Mauricio Pereira');
INSERT INTO pessoa (cpf, email, nome) VALUES ('60185258018', 'antonio_soares@moderna.com.br', 'Antonio José Campos Soares');
INSERT INTO pessoa (cpf, email, nome) VALUES ('28174735070', 'pdias@moderna.com.br', 'Paulo Luiz Dias');
INSERT INTO pessoa (cpf, email, nome) VALUES ('72076673610', 'roberto.costa@outlook.com', 'Roberto Bruno Vieira da Costa');
INSERT INTO pessoa (cpf, email, nome) VALUES ('98304435403', 'julio.moura@gmail.com', 'Julio Soares de Moura');
INSERT INTO pessoa (cpf, email, nome) VALUES ('95582581057', 'laura.rocha@globo.com', 'Laura Martins Rocha');
INSERT INTO pessoa (cpf, email, nome) VALUES ('83384073991', 'jorge.nascimento@hotmail.com', 'Jorge Gabriel da Silva Nascimento');
INSERT INTO pessoa (cpf, email, nome) VALUES ('39125173804', 'arodrigues@r7.com', 'Ana Rodrigues');
INSERT INTO pessoa (cpf, email, nome) VALUES ('73990582100', 'gilbertosilva@outlook.com', 'Gilberto Cardoso da Silva');
INSERT INTO pessoa (cpf, email, nome) VALUES ('32729725369', 'adriane_rodrigues@bol.com.br', 'Adriane Priscila Gomes Rodrigues');
INSERT INTO pessoa (cpf, email, nome) VALUES ('47777741470', 'lucas_azevedo@r7.com', 'Lucas Marcos Azevedo');
INSERT INTO pessoa (cpf, email, nome) VALUES ('41491103795', 'aline.souza@terra.com.br', 'Aline Rocha da Mota Souza');
INSERT INTO pessoa (cpf, email, nome) VALUES ('02342751389', 'felipefreitas@comercial.com.br', 'Felipe Francisco Ribeiro Freitas');
INSERT INTO pessoa (cpf, email, nome) VALUES ('53766194941', 'arthur.santos318@ig.com.br', 'Arthur Ferreira dos Santos');
INSERT INTO pessoa (cpf, email, nome) VALUES ('06943780115', 'fabio_andrade@empresa.com.br', 'Fabio de Andrade');
INSERT INTO pessoa (cpf, email, nome) VALUES ('62805389905', 'mazevedo@hotmail.com', 'Marcia de Almeida Azevedo');
INSERT INTO pessoa (cpf, email, nome) VALUES ('18744424876', 'julianamoreira@moderna.com.br', 'Juliana Adriane Campos Moreira');
INSERT INTO pessoa (cpf, email, nome) VALUES ('21852620927', 'vjesus@empresa.com.br', 'Valeria Martins de Jesus');
INSERT INTO pessoa (cpf, email, nome) VALUES ('96276937665', 'bruno.ribeiro@comercial.com.br', 'Bruno Ribeiro');
INSERT INTO pessoa (cpf, email, nome) VALUES ('27944037530', 'valeria.rocha312@empresa.com.br', 'Valeria Maria Cardoso Rocha');
INSERT INTO pessoa (cpf, email, nome) VALUES ('44603128088', 'beatriz.freitas300@moderna.com.br', 'Beatriz Adriane Lima Freitas');
INSERT INTO pessoa (cpf, email, nome) VALUES ('23018218973', 'antonio.freitas932@negocio.com.br', 'Antonio Paulo Araújo Freitas');
INSERT INTO pessoa (cpf, email, nome) VALUES ('83037570083', 'priscila.pereira@globo.com', 'Priscila Leticia Costa Pereira');
INSERT INTO pessoa (cpf, email, nome) VALUES ('98684151950', 'paulo_ribeiro@yahoo.com.br', 'Paulo Diego Nascimento Ribeiro');
INSERT INTO pessoa (cpf, email, nome) VALUES ('50130357081', 'mcampos@empresa.com.br', 'Moreno Nascimento Campos');
INSERT INTO pessoa (cpf, email, nome) VALUES ('98848377912', 'marianaalmeida@gmail.com', 'Mariana Francisca Soares de Almeida');
INSERT INTO pessoa (cpf, email, nome) VALUES ('38398736062', 'eduardo.almeida267@empresa.com.br', 'Eduardo Daniel de Almeida');
INSERT INTO pessoa (cpf, email, nome) VALUES ('68200390268', 'jose_souza@negocio.com.br', 'José Gilberto Souza');
INSERT INTO pessoa (cpf, email, nome) VALUES ('88431873680', 'pgomes@comercial.com.br', 'Paulo Jamil de Carvalho Gomes');
INSERT INTO pessoa (cpf, email, nome) VALUES ('41609482352', 'jose.monteiro@gmail.com', 'José Monteiro');
INSERT INTO pessoa (cpf, email, nome) VALUES ('29712142493', 'nelson.barbosa345@r7.com', 'Nelson Eduardo de Oliveira Barbosa');
INSERT INTO pessoa (cpf, email, nome) VALUES ('49125043862', 'jose_reis@comercial.com.br', 'José Mauricio Oliveira Reis');
INSERT INTO pessoa (cpf, email, nome) VALUES ('92782622773', 'laura.rodrigues@comercial.com.br', 'Laura Dias Rodrigues');
INSERT INTO pessoa (cpf, email, nome) VALUES ('35083879921', 'leticia_luz@empresa.com.br', 'Leticia da Luz');
INSERT INTO pessoa (cpf, email, nome) VALUES ('84513631724', 'camilacosta@empresa.com.br', 'Camila Laura Azevedo Costa');
INSERT INTO pessoa (cpf, email, nome) VALUES ('23527687300', 'diego_pereira@hotmail.com', 'Diego Azevedo Pereira');
INSERT INTO pessoa (cpf, email, nome) VALUES ('48039882699', 'rafael.melo@terra.com.br', 'Rafael Reis de Moura Melo');
INSERT INTO pessoa (cpf, email, nome) VALUES ('43366536233', 'sabrina.jesus@empresa.com.br', 'Sabrina de Jesus');
INSERT INTO pessoa (cpf, email, nome) VALUES ('21553569865', 'jessica.castro@bol.com.br', 'Jessica Bianca Castro');
INSERT INTO pessoa (cpf, email, nome) VALUES ('61311056858', 'maria_rodrigues@comercial.com.br', 'Maria Rodrigues');
INSERT INTO pessoa (cpf, email, nome) VALUES ('91156504805', 'sergioramos@yahoo.com.br', 'Sergio Martins Ramos');
INSERT INTO pessoa (cpf, email, nome) VALUES ('15033770403', 'francisca.castro@r7.com', 'Francisca Jessica Lopes Castro');
INSERT INTO pessoa (cpf, email, nome) VALUES ('02926507607', 'bianca.barbosa@corporativo.com.br', 'Bianca Barbosa');
INSERT INTO pessoa (cpf, email, nome) VALUES ('56232473426', 'bianca.moreira@gmail.com', 'Bianca Ana Mendes Moreira');
INSERT INTO pessoa (cpf, email, nome) VALUES ('16310464892', 'laura.goncalves255@globo.com', 'Laura Nascimento Gonçalves');
INSERT INTO pessoa (cpf, email, nome) VALUES ('28577859843', 'manoel.monteiro780@hotmail.com', 'Manoel Daniel dos Santos Monteiro');
INSERT INTO pessoa (cpf, email, nome) VALUES ('79173432946', 'gabriela_souza@hotmail.com', 'Gabriela Souza');
INSERT INTO pessoa (cpf, email, nome) VALUES ('51275666647', 'carlos.cavalcanti@ig.com.br', 'Carlos Francisco Teixeira Cavalcanti');
INSERT INTO pessoa (cpf, email, nome) VALUES ('42053968729', 'aliramos@empresa.com.br', 'Ali Barbosa Correia Ramos');
INSERT INTO pessoa (cpf, email, nome) VALUES ('83110986469', 'fsilva@bol.com.br', 'Francisco Vieira Silva');
INSERT INTO pessoa (cpf, email, nome) VALUES ('80731669096', 'gabrielvieira@ig.com.br', 'Gabriel Alves Vieira');
INSERT INTO pessoa (cpf, email, nome) VALUES ('54008446850', 'jramos@bol.com.br', 'Jessica Luana Carvalho Ramos');
INSERT INTO pessoa (cpf, email, nome) VALUES ('51284302008', 'lucas.costa125@terra.com.br', 'Lucas Gomes Costa');
INSERT INTO pessoa (cpf, email, nome) VALUES ('56523565882', 'tatianepereira@hotmail.com', 'Tatiane Renata Pereira');
INSERT INTO pessoa (cpf, email, nome) VALUES ('77564631295', 'caroline.almeida140@comercial.com.br', 'Caroline de Almeida');
INSERT INTO pessoa (cpf, email, nome) VALUES ('25414393001', 'fernanda.vieira412@outlook.com', 'Fernanda Teixeira Vieira');
INSERT INTO pessoa (cpf, email, nome) VALUES ('67229812070', 'jorgevieira@corporativo.com.br', 'Jorge Carvalho Vieira');
INSERT INTO pessoa (cpf, email, nome) VALUES ('89116260740', 'beatriz.barbosa@globo.com', 'Beatriz Natalia Barbosa');
INSERT INTO pessoa (cpf, email, nome) VALUES ('87011844589', 'renata_santos@corporativo.com.br', 'Renata Francisca Gomes Santos');
INSERT INTO pessoa (cpf, email, nome) VALUES ('77698625745', 'lucasmoura@globo.com', 'Lucas de Moura');
INSERT INTO pessoa (cpf, email, nome) VALUES ('35879213773', 'bsantos@moderna.com.br', 'Beatriz Sabrina de Lima dos Santos');
INSERT INTO pessoa (cpf, email, nome) VALUES ('58019180605', 'daniel_almeida@gmail.com', 'Daniel Almeida');
INSERT INTO pessoa (cpf, email, nome) VALUES ('47469421530', 'jaqueline.mendes@uol.com.br', 'Jaqueline Tatiane Mendes');
INSERT INTO pessoa (cpf, email, nome) VALUES ('22409766676', 'rodrigo_jesus@outlook.com', 'Rodrigo de Jesus');
INSERT INTO pessoa (cpf, email, nome) VALUES ('80046385622', 'gsouza@ig.com.br', 'Gabriela Natalia Alves de Souza');
INSERT INTO pessoa (cpf, email, nome) VALUES ('19582955589', 'gilberto.almeida318@moderna.com.br', 'Gilberto da Rocha Almeida');
INSERT INTO pessoa (cpf, email, nome) VALUES ('87532479730', 'leonardo.almeida@empresa.com.br', 'Leonardo Pinto Freitas Almeida');
INSERT INTO pessoa (cpf, email, nome) VALUES ('13454974151', 'lteixeira@comercial.com.br', 'Larissa dos Santos Teixeira');
INSERT INTO pessoa (cpf, email, nome) VALUES ('06706263508', 'lucas_barbosa@yahoo.com.br', 'Lucas de Almeida Barbosa');
INSERT INTO pessoa (cpf, email, nome) VALUES ('07114282559', 'beatriz.alves860@comercial.com.br', 'Beatriz Gomes Alves');
INSERT INTO pessoa (cpf, email, nome) VALUES ('45124143126', 'diego.costa641@hotmail.com', 'Diego Moreira Costa');
INSERT INTO pessoa (cpf, email, nome) VALUES ('21745091998', 'brunooliveira@outlook.com', 'Bruno Felipe Castro Oliveira');
INSERT INTO pessoa (cpf, email, nome) VALUES ('64948853658', 'leticiasouza@globo.com', 'Leticia Carla Ferreira Souza');
INSERT INTO pessoa (cpf, email, nome) VALUES ('35987566231', 'jorge.mota762@terra.com.br', 'Jorge Souza da Costa da Mota');
INSERT INTO pessoa (cpf, email, nome) VALUES ('32928361316', 'julio_almeida@moderna.com.br', 'Julio de Moura Almeida');
INSERT INTO pessoa (cpf, email, nome) VALUES ('35584448419', 'sergio.martins247@uol.com.br', 'Sergio Fernandes Martins');
INSERT INTO pessoa (cpf, email, nome) VALUES ('69726222478', 'lucas_santos@empresa.com.br', 'Lucas Dias Santos');
INSERT INTO pessoa (cpf, email, nome) VALUES ('59813229500', 'rpinto@empresa.com.br', 'Raimundo Pinto');
INSERT INTO pessoa (cpf, email, nome) VALUES ('78588930501', 'gabriel.carvalho@moderna.com.br', 'Gabriel Araújo de Carvalho');
INSERT INTO pessoa (cpf, email, nome) VALUES ('11636350143', 'jaqueline.ramos@yahoo.com.br', 'Jaqueline Reis da Costa Ramos');
INSERT INTO pessoa (cpf, email, nome) VALUES ('11034692747', 'gcosta@moderna.com.br', 'Gustavo Jorge Costa');
INSERT INTO pessoa (cpf, email, nome) VALUES ('75682158903', 'raimundo_freitas@ig.com.br', 'Raimundo Freitas');
INSERT INTO pessoa (cpf, email, nome) VALUES ('62337039137', 'julio_soares@hotmail.com', 'Julio Soares');
INSERT INTO pessoa (cpf, email, nome) VALUES ('34621920278', 'valeria.melo900@globo.com', 'Valeria Azevedo Melo');
INSERT INTO pessoa (cpf, email, nome) VALUES ('91554546311', 'vanessa.vieira39@yahoo.com.br', 'Vanessa Sandra Vieira');
INSERT INTO pessoa (cpf, email, nome) VALUES ('10887756913', 'jaraujo@yahoo.com.br', 'José de Almeida Araújo');
INSERT INTO pessoa (cpf, email, nome) VALUES ('49028876731', 'sergio.lima@negocio.com.br', 'Sergio Manoel Teixeira Carvalho de Lima');
INSERT INTO pessoa (cpf, email, nome) VALUES ('60706136357', 'beatriz_melo@uol.com.br', 'Beatriz Teixeira Melo');
INSERT INTO pessoa (cpf, email, nome) VALUES ('63302583761', 'lramos@negocio.com.br', 'Lucas Ramos');
INSERT INTO pessoa (cpf, email, nome) VALUES ('24312389039', 'daniela.souza785@outlook.com', 'Daniela Souza');
INSERT INTO pessoa (cpf, email, nome) VALUES ('13911677758', 'luciana.oliveira@ig.com.br', 'Luciana Sandra Oliveira de Oliveira');
INSERT INTO pessoa (cpf, email, nome) VALUES ('66042170783', 'gabriel.carvalho622@ig.com.br', 'Gabriel do Nascimento Carvalho');
INSERT INTO pessoa (cpf, email, nome) VALUES ('36393018542', 'morenolima@hotmail.com', 'Moreno Dias de Lima');
INSERT INTO pessoa (cpf, email, nome) VALUES ('93499610400', 'ali.lima@r7.com', 'Ali Campos de Lima');
INSERT INTO pessoa (cpf, email, nome) VALUES ('87366577944', 'fcosta@moderna.com.br', 'Francisco Rodrigues da Costa');
INSERT INTO pessoa (cpf, email, nome) VALUES ('07884611414', 'amanda.moreira@uol.com.br', 'Amanda Mariana Araújo Moreira');
INSERT INTO pessoa (cpf, email, nome) VALUES ('39498765294', 'csantos@outlook.com', 'Camila dos Santos');
INSERT INTO pessoa (cpf, email, nome) VALUES ('98552289954', 'mramos@terra.com.br', 'Marcos da Costa Ramos');
INSERT INTO pessoa (cpf, email, nome) VALUES ('66396799570', 'luciana.lima322@moderna.com.br', 'Luciana Julia de Lima');
INSERT INTO pessoa (cpf, email, nome) VALUES ('66681750150', 'luana.reis@yahoo.com.br', 'Luana Nascimento Reis');
INSERT INTO pessoa (cpf, email, nome) VALUES ('43169118641', 'gabriel_soares@hotmail.com', 'Gabriel Alves Freitas Soares');
INSERT INTO pessoa (cpf, email, nome) VALUES ('78052759803', 'gsilva@terra.com.br', 'Gustavo Rocha da Silva');
INSERT INTO pessoa (cpf, email, nome) VALUES ('44021512101', 'nicolas.martins823@negocio.com.br', 'Nicolas Martins');
INSERT INTO pessoa (cpf, email, nome) VALUES ('56207634390', 'camila_costa@comercial.com.br', 'Camila Cavalcanti Costa');
INSERT INTO pessoa (cpf, email, nome) VALUES ('66935330866', 'fcorreia@uol.com.br', 'Francisco Moreno Correia');
INSERT INTO pessoa (cpf, email, nome) VALUES ('29943616202', 'maria.moura@moderna.com.br', 'Maria Soares de Moura');
INSERT INTO pessoa (cpf, email, nome) VALUES ('78319837677', 'julia_lima@gmail.com', 'Julia de Oliveira Lima');
INSERT INTO pessoa (cpf, email, nome) VALUES ('42337386180', 'natalia.cavalcanti184@terra.com.br', 'Natalia Laura Dias Cavalcanti');
INSERT INTO pessoa (cpf, email, nome) VALUES ('50313077061', 'juliopereira@uol.com.br', 'Julio Pereira');
INSERT INTO pessoa (cpf, email, nome) VALUES ('99870808980', 'jbarbosa@globo.com', 'José Barbosa');
INSERT INTO pessoa (cpf, email, nome) VALUES ('42555987118', 'fmota@negocio.com.br', 'Felipe do Nascimento Martins da Mota');
INSERT INTO pessoa (cpf, email, nome) VALUES ('01144813506', 'priscilaoliveira@uol.com.br', 'Priscila Adriana Santos de Oliveira');
INSERT INTO pessoa (cpf, email, nome) VALUES ('87756503635', 'luis_ribeiro@hotmail.com', 'Luis Ribeiro');
INSERT INTO pessoa (cpf, email, nome) VALUES ('93942330911', 'simone.gomes@comercial.com.br', 'Simone de Moura Gomes');
INSERT INTO pessoa (cpf, email, nome) VALUES ('29841941953', 'patricia.ramos566@r7.com', 'Patricia Gonçalves Ramos');
INSERT INTO pessoa (cpf, email, nome) VALUES ('13533004805', 'ali_soares@moderna.com.br', 'Ali Gabriel Soares');
INSERT INTO pessoa (cpf, email, nome) VALUES ('57898307062', 'laraujo@gmail.com', 'Laura da Costa Araújo');
INSERT INTO pessoa (cpf, email, nome) VALUES ('76101294374', 'fabio_rocha@empresa.com.br', 'Fabio Melo Rocha');
INSERT INTO pessoa (cpf, email, nome) VALUES ('10858568870', 'sergioalmeida@bol.com.br', 'Sergio Cavalcanti de Almeida');
INSERT INTO pessoa (cpf, email, nome) VALUES ('20485582406', 'marciagomes@ig.com.br', 'Marcia Reis Gomes');
INSERT INTO pessoa (cpf, email, nome) VALUES ('18069916753', 'nicolas.almeida@globo.com', 'Nicolas de Almeida');
INSERT INTO pessoa (cpf, email, nome) VALUES ('20757815324', 'luciana.ribeiro387@gmail.com', 'Luciana Jessica de Oliveira Ribeiro');
INSERT INTO pessoa (cpf, email, nome) VALUES ('15610899150', 'luizsouza@negocio.com.br', 'Luiz Moreno Ferreira Gomes Souza');
INSERT INTO pessoa (cpf, email, nome) VALUES ('72981459244', 'marcia.araujo105@r7.com', 'Marcia de Moura Araújo');
INSERT INTO pessoa (cpf, email, nome) VALUES ('19846779771', 'antoniorodrigues@empresa.com.br', 'Antonio Vieira Rodrigues');
INSERT INTO pessoa (cpf, email, nome) VALUES ('84835237102', 'mrocha@terra.com.br', 'Moreno Silva Rodrigues Rocha');
INSERT INTO pessoa (cpf, email, nome) VALUES ('90377663239', 'anamendes@globo.com', 'Ana Natalia Melo Almeida Mendes');
INSERT INTO pessoa (cpf, email, nome) VALUES ('41118460413', 'leonardo.carvalho@terra.com.br', 'Leonardo Alves de Carvalho');
INSERT INTO pessoa (cpf, email, nome) VALUES ('44467841105', 'diego.luz@uol.com.br', 'Diego da Mota da Luz');
INSERT INTO pessoa (cpf, email, nome) VALUES ('76626358995', 'diego.goncalves@r7.com', 'Diego do Nascimento Gonçalves');
INSERT INTO pessoa (cpf, email, nome) VALUES ('39435759939', 'camila.goncalves169@globo.com', 'Camila Priscila Costa Cardoso Gonçalves');
INSERT INTO pessoa (cpf, email, nome) VALUES ('38393093287', 'jaquelinemelo@hotmail.com', 'Jaqueline Sandra da Silva Campos Melo');
INSERT INTO pessoa (cpf, email, nome) VALUES ('68853486198', 'dcastro@r7.com', 'Daniel Pinto Castro');
INSERT INTO pessoa (cpf, email, nome) VALUES ('66337491718', 'roliveira@gmail.com', 'Roberto Jorge Alves de Oliveira');
INSERT INTO pessoa (cpf, email, nome) VALUES ('75598956543', 'eduardo.pereira320@gmail.com', 'Eduardo Roberto Campos Pereira');
INSERT INTO pessoa (cpf, email, nome) VALUES ('37918958934', 'marcos.araujo@terra.com.br', 'Marcos Ferreira Araújo');
INSERT INTO pessoa (cpf, email, nome) VALUES ('78605029501', 'leonardo.soares@yahoo.com.br', 'Leonardo Teixeira Soares');
INSERT INTO pessoa (cpf, email, nome) VALUES ('82045547299', 'guilherme_soares@globo.com', 'Guilherme Vieira Soares');
INSERT INTO pessoa (cpf, email, nome) VALUES ('78902490475', 'julia.castro@negocio.com.br', 'Julia Lopes Castro');
INSERT INTO pessoa (cpf, email, nome) VALUES ('04835723651', 'carla.mota@empresa.com.br', 'Carla Carla Fernandes da Mota');
INSERT INTO pessoa (cpf, email, nome) VALUES ('81071660357', 'juliana.ramos@corporativo.com.br', 'Juliana Ramos');
INSERT INTO pessoa (cpf, email, nome) VALUES ('09226298700', 'aline.costa816@comercial.com.br', 'Aline Renata de Carvalho da Costa');
INSERT INTO pessoa (cpf, email, nome) VALUES ('33776350504', 'luis.lima389@empresa.com.br', 'Luis Lima');
INSERT INTO pessoa (cpf, email, nome) VALUES ('12070775852', 'luiz_pinto@corporativo.com.br', 'Luiz Vieira Pinto');
INSERT INTO pessoa (cpf, email, nome) VALUES ('49138244144', 'larissa.cardoso@terra.com.br', 'Larissa Ana Cardoso');
INSERT INTO pessoa (cpf, email, nome) VALUES ('15941679823', 'simone_carvalho@uol.com.br', 'Simone Caroline de Carvalho');
INSERT INTO pessoa (cpf, email, nome) VALUES ('93864309247', 'paulomendes@empresa.com.br', 'Paulo Mendes');
INSERT INTO pessoa (cpf, email, nome) VALUES ('51827144246', 'lucassilva@outlook.com', 'Lucas Enzo da Mota Rocha Silva');
INSERT INTO pessoa (cpf, email, nome) VALUES ('89704929846', 'bianca_vieira@negocio.com.br', 'Bianca Silva Vieira');
INSERT INTO pessoa (cpf, email, nome) VALUES ('14372664958', 'cristianesouza@ig.com.br', 'Cristiane Luciana de Souza');
INSERT INTO pessoa (cpf, email, nome) VALUES ('16756847236', 'fmendes@comercial.com.br', 'Fernanda de Oliveira Mendes');
INSERT INTO pessoa (cpf, email, nome) VALUES ('19832469139', 'faraujo@comercial.com.br', 'Fabiano Araújo');
INSERT INTO pessoa (cpf, email, nome) VALUES ('09896279934', 'valeria.jesus21@globo.com', 'Valeria Cristiane de Jesus');
INSERT INTO pessoa (cpf, email, nome) VALUES ('63075201839', 'jaquelinealmeida@ig.com.br', 'Jaqueline Daniela de Lima Cardoso Almeida');
INSERT INTO pessoa (cpf, email, nome) VALUES ('39735624745', 'valeriareis@outlook.com', 'Valeria de Andrade Reis');
INSERT INTO pessoa (cpf, email, nome) VALUES ('98942107168', 'bruno.oliveira366@r7.com', 'Bruno Mendes Carvalho de Oliveira');
INSERT INTO pessoa (cpf, email, nome) VALUES ('12948373549', 'lucas.santos@comercial.com.br', 'Lucas Raimundo da Silva dos Santos');
INSERT INTO pessoa (cpf, email, nome) VALUES ('12323117580', 'sabrina.almeida@r7.com', 'Sabrina Souza Almeida');
